export const ICONS = {

    //Tab icons
    home: 'home',
    categories: 'th-large',
    offers: 'gift',
    account: 'user',
    cart: 'cart-plus',
    search: 'search',
    wishlist: 'heart',
    logOut: 'power-off',
    address: 'map-marker',
    payment: 'credit-card',
    profile: 'user-circle',
    language: 'globe',
    menu: "ellipsis-v",
    rightArrow: "chevron-right",
    leftArrow: 'chevron-left',
    upArrow: 'chevron-up',
    downArrow: 'chevron-down',
    help: 'question-circle',
    return: 'undo',
    orders: 'archive',
    filter: 'filter',
    sorting: 'sort-amount-down',
    graidH: 'sliders-h',
    graidV: 'microsoft',



    info: 'info-circle',
    clock: 'clock',

    settings: 'cellphone-settings-variant',
    about: 'information-outline',
    contact: 'phone',
    terms: 'library',
    share: 'share-variant',
    slider: 'sliders-h',
    filter: 'filter',
    facebook: 'facebook',
    youtube: 'youtube',
    twitter: 'twitter',
    google: 'google-plus',
    eyeOn: 'eye-outline',
    eyeOff: 'eye-off-outline',
    child: 'account',
    checkBox: 'radiobox-blank',
    checkBoxMarked: 'radiobox-marked',
    unchecked: "radiobox-blank",
    checked: "check",
    imagePlaceHolder: 'image',
    noData: 'box-open',
    circle: 'dot-circle',
    pluse: 'plus-circle',

    close:'times-circle',

}